# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/CategoryDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CategoryDialog(object):
    def setupUi(self, CategoryDialog):
        CategoryDialog.setObjectName("CategoryDialog")
        CategoryDialog.resize(400, 300)
        CategoryDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(CategoryDialog)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(CategoryDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nameEdit = QtWidgets.QLineEdit(CategoryDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.label_2 = QtWidgets.QLabel(CategoryDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textEdit = QtWidgets.QPlainTextEdit(CategoryDialog)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.label_3 = QtWidgets.QLabel(CategoryDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choiceFileButton = QtWidgets.QPushButton(CategoryDialog)
        self.choiceFileButton.setObjectName("choiceFileButton")
        self.horizontalLayout.addWidget(self.choiceFileButton)
        self.choisenFIleName = QtWidgets.QLineEdit(CategoryDialog)
        self.choisenFIleName.setEnabled(True)
        self.choisenFIleName.setAutoFillBackground(False)
        self.choisenFIleName.setStyleSheet("background: transparent; border: 0;")
        self.choisenFIleName.setFrame(True)
        self.choisenFIleName.setReadOnly(True)
        self.choisenFIleName.setObjectName("choisenFIleName")
        self.horizontalLayout.addWidget(self.choisenFIleName)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(CategoryDialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setAcceptDrops(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CategoryDialog)
        self.buttonBox.accepted.connect(CategoryDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(CategoryDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CategoryDialog)

    def retranslateUi(self, CategoryDialog):
        _translate = QtCore.QCoreApplication.translate
        CategoryDialog.setWindowTitle(_translate("CategoryDialog", "Dialog"))
        self.label.setText(_translate("CategoryDialog", "Название категории"))
        self.label_2.setText(_translate("CategoryDialog", "Описание"))
        self.label_3.setText(_translate("CategoryDialog", "Изображение"))
        self.choiceFileButton.setText(_translate("CategoryDialog", "Выбрать"))
