# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ChoicePile.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pile(object):
    def setupUi(self, Pile):
        Pile.setObjectName("Pile")
        Pile.resize(150, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Pile.sizePolicy().hasHeightForWidth())
        Pile.setSizePolicy(sizePolicy)
        Pile.setMaximumSize(QtCore.QSize(150, 150))
        Pile.setMouseTracking(False)
        self.gridLayout = QtWidgets.QGridLayout(Pile)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.imageFrame = QtWidgets.QFrame(Pile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageFrame.sizePolicy().hasHeightForWidth())
        self.imageFrame.setSizePolicy(sizePolicy)
        self.imageFrame.setMinimumSize(QtCore.QSize(100, 100))
        self.imageFrame.setMaximumSize(QtCore.QSize(150, 150))
        self.imageFrame.setStyleSheet("border: 1px solid")
        self.imageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageFrame.setObjectName("imageFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.imageFrame)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pileTitle = QtWidgets.QLabel(self.imageFrame)
        self.pileTitle.setMinimumSize(QtCore.QSize(0, 0))
        self.pileTitle.setMaximumSize(QtCore.QSize(300, 20))
        self.pileTitle.setAutoFillBackground(True)
        self.pileTitle.setStyleSheet("border: none;\n"
"background-color: #1212ce;\n"
"color: rgb(255, 255, 255);")
        self.pileTitle.setFrameShape(QtWidgets.QFrame.Box)
        self.pileTitle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pileTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.pileTitle.setWordWrap(True)
        self.pileTitle.setObjectName("pileTitle")
        self.gridLayout_2.addWidget(self.pileTitle, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.imageFrame, 0, 0, 1, 1)

        self.retranslateUi(Pile)
        QtCore.QMetaObject.connectSlotsByName(Pile)

    def retranslateUi(self, Pile):
        _translate = QtCore.QCoreApplication.translate
        Pile.setWindowTitle(_translate("Pile", "Form"))
        self.pileTitle.setText(_translate("Pile", "TextLabel"))
