# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ProductDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProductDialog(object):
    def setupUi(self, ProductDialog):
        ProductDialog.setObjectName("ProductDialog")
        ProductDialog.resize(400, 200)
        ProductDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProductDialog)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(ProductDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.nameEdit = QtWidgets.QLineEdit(ProductDialog)
        self.nameEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.label_3 = QtWidgets.QLabel(ProductDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choiceFileButton = QtWidgets.QPushButton(ProductDialog)
        self.choiceFileButton.setObjectName("choiceFileButton")
        self.horizontalLayout.addWidget(self.choiceFileButton)
        self.choisenFIleName = QtWidgets.QLineEdit(ProductDialog)
        self.choisenFIleName.setEnabled(True)
        self.choisenFIleName.setAutoFillBackground(False)
        self.choisenFIleName.setStyleSheet("background: transparent; border: 0;")
        self.choisenFIleName.setFrame(True)
        self.choisenFIleName.setReadOnly(True)
        self.choisenFIleName.setObjectName("choisenFIleName")
        self.horizontalLayout.addWidget(self.choisenFIleName)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(ProductDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.priceSpinBox = QtWidgets.QSpinBox(ProductDialog)
        self.priceSpinBox.setMinimumSize(QtCore.QSize(150, 0))
        self.priceSpinBox.setMaximum(999999999)
        self.priceSpinBox.setObjectName("priceSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.priceSpinBox)
        self.label_4 = QtWidgets.QLabel(ProductDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.categoryComboBox = QtWidgets.QComboBox(ProductDialog)
        self.categoryComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.categoryComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(ProductDialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setAcceptDrops(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ProductDialog)
        self.buttonBox.accepted.connect(ProductDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ProductDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProductDialog)

    def retranslateUi(self, ProductDialog):
        _translate = QtCore.QCoreApplication.translate
        ProductDialog.setWindowTitle(_translate("ProductDialog", "Dialog"))
        self.label.setText(_translate("ProductDialog", "Название продукта"))
        self.label_3.setText(_translate("ProductDialog", "Изображение"))
        self.choiceFileButton.setText(_translate("ProductDialog", "Выбрать"))
        self.label_2.setText(_translate("ProductDialog", "Цена"))
        self.label_4.setText(_translate("ProductDialog", "Категория"))
